# Generated by Django 5.1.1 on 2024-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femal')], default='', max_length=1),
        ),
    ]
