# Generated by Django 5.1.1 on 2024-09-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0002_alter_userprofile_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fav_book',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='how_he_look',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
