# Generated by Django 5.1.1 on 2024-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_app', '0003_userprofile_country_userprofile_fav_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Current_goal',
            new_name='current_goal',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='My_golden_rule',
            new_name='my_golden_rule',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=6),
        ),
    ]
